version: '3.7'

services:
  studentmanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '53676:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_studentmanagement
      - ACCEPT_EULA=Y
    volumes:
      - studentmanagement-data:/var/lib/sqlserver/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "53684:5775/udp"
      - "53683:6831/udp"
      - "53685:6832/udp"
      - "53686:5778"
      - "53687:16686"
      - "53688:14250"
      - "53689:14268"
      - "53690:14269"
      - "53691:9411"

        
volumes:
  # compose volumes marker - do not delete
  studentmanagement-data:
